### ISSUE TITLE
Thirdeye Setup, Documentation, Examples

### ISSUE THREAD

**Issue by cliu587** [linkedin/pinot#64]
I have been trying to get Thirdeye running with an example dataset. I have encountered some difficulties. Some of which are resolved, and I've written them down here for completeness, while others are requests for help. I can create new issues for some of these, if required.

- The Thirdeye Hadoop jobs does not take in Hadoop job memory settings (e.g `-Dmapreduce.map.memory.mb`), and `job.properties` memory settings are not configured.

- No example of `config.yml`. Here is one that worked for me.
```
collection: registrations
dimensions:
  - name: MY_DIM_1
  - name: MY_DIM_2
metrics:
  - name: count
    type: INT
time:
  columnName: date
  input:
    size: 1
    unit: HOURS
  bucket:
    size: 1
    unit: HOURS
  retention:
    size: 365
    unit: DAYS
rollup:
  functionClass: com.linkedin.thirdeye.bootstrap.rollup.TotalAggregateBasedRollupFunction
  functionConfig:
    metricName: "count"
    threshold: "100"
split:
  threshold: 3
```
I am unsure of what exactly can be put here, and there was a `TopKRollupSpec` that was interesting...

- In the bootstrap phases, I had to add some extra properties to `job.properties`, or the jobs will error out. Overall, I added the following:
```
thirdeye.time.min=2010-01-01
thirdeye.time.max=2020-01-01
thirdeye.dimension.index.ref=data_2010-01-01-000000_2020-01-01-000000
thirdeye.flow.schedule=MONTHLY
```
In particular, I believe the first two lines were needed in the `analysis` job, as per https://github.com/linkedin/pinot/blob/master/thirdeye/thirdeye-bootstrap/src/main/java/com/linkedin/thirdeye/bootstrap/ThirdEyeJob.java#L1131

The 3rd line was required for the `startree_bootstrap_phase1` and `startree_bootstrap_phase2` job
, and `thirdeye.flow.schedule` was needed for the `server_package` job.

- Without Kerberos set up in our Hadoop cluster, I had to use `server_package` job in the `thirdeye-bootstrap` package to combine the `{thirdeye.root}/{thirdeye.collection}/METRIC_INDEX/DATE_RANGE/startree_bootstrap_phase2/data-x.tar.gz` files to a single `data.tar.gz`.
Then I had to POST the endpoint `/collections/{thirdeye.collection}` with that `data.tar.gz` file, and after a restart of `thirdeye-server`, the collection got picked up.
Commands I used:
```
curl -XPOST \
  --data-binary @{MY_PATH_TO}/config.yml \
  -H 'Content-Type:application/octet-stream' \
  localhost:8080/collections/registrations
curl -XPOST \
  --data-binary @{MY_PATH_TO}/data.tar.gz \
  -H 'Content-Type:application/octet-stream' \
  localhost:8080/collections/registrations/data/{START_MILLIS}/{END_MILLIS}
```
Where {START_MILLIS}, {END_MILLIS} correspond to milliseconds from Epoch of the dates I set for `thirdeye.time.min` and `thirdeye.time.max`, respectively.

- Just having `thirdeye-server` doesn't seem to be enough if I want the dashboard UI. I had to start `thirdeye-dashboard` with its own YAML configs (default config will make it start at port 8080, which conflicted with `thirdeye-server`)
Configs I used:
```
serverUri: http://localhost:8080
server:
  applicationConnectors:
  - type: http
    port: 8082
  adminConnectors:
  - type: http
    port: 9001
funnelConfigRoot: SOME_FOLDER
```
- The `funnelConfigRoot` was required, or the `FunnelsDataProvider` will not be instantiated, even if the folder doesn't contain a `funnel.yml`. I believe this behavior is because of https://github.com/linkedin/pinot/blob/master/thirdeye/thirdeye-dashboard/src/main/java/com/linkedin/thirdeye/dashboard/ThirdEyeDashboard.java#L73
- I got some `SocketTimeoutException` for queries that `thirdeye-dashboard` was making to `thirdeye-server`, but they seem to have disappeared now. Not sure if there is a place to set timeout
- In general, there is a lot of 'custom dashboard' or 'custom funnel' things that I am unsure how to get working. Some documentation there would be great.
- My dataset I believe is sparse enough that for some combination of dimension values, there are 0 rows.  This resulted in a cryptic datatable error message of `DataTables warning: table id=tabularView-metric_0 - Requested unknown parameter '8' for row 396. For more information about this error, please see http://datatables.net/tn/4`
Using the chrome console, I got an error message of:
`"FreeMarker template error (DEBUG mode; use RETHROW in production!): The following has evaluated to null or missing: ==&gt; cell.statsMap['volume_difference'] [in template "com/linkedin/thirdeye/dashboard/views/dimension/heat-map.ftl" at line 162, column 44]...`
The full message is available here: [https://gist.github.com/cliu587/704d0855fc9ae4d8bddc](https://gist.github.com/cliu587/704d0855fc9ae4d8bddc)

I am pretty stuck on the last part, but it only affects the heatmap tab.
The Contributors tab works fine.

Hopefully this is helpful!
